version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=splitni-to
    ports:
      - "5432:5432"
    hostname: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d splitni-to" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./backend/migrations:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    command: sh -c "sleep 10 && ./main"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/splitni-to

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend